### ISSUE TITLE
Error handling around exec

### ISSUE THREAD

**Issue by JohnOH** [falzm/burl#2]
I too love your script, reduced the loading on my RasPi 256k from 100% down to 1%.

I have an infrequent issue around "    exec 3<>/dev/tcp/${host}/${port}  " in that an error occurs shown by:
```
/usr/bin/burl: line 20: api.thingspeak.com: Name or service not known
/usr/bin/burl: line 20: /dev/tcp/api.thingspeak.com/80: Invalid argument
```
I admit that I don't yet grasp how you do this magic and so I can't see how to add some error handling after the exec.

I respect your statements on this being a toy project but you may have time to share your thoughts on my issue - I hope so.

**Comment by falzm** [comment]
Hi @JohnOH 

Are you actually using a *Bash* shell, not a busybox or some kind of minimal shell? If Bash, which version? Is the error you're facing permanent, or does it occur from time to time?

Also, are you using the latest version of the script? [Line 20 in the current version](https://github.com/falzm/burl/blob/master/burl#L20) doesn't really relate to the error you're reporting.

**Comment by JohnOH** [comment]
Good spot, I updated the original script to include the optional port & crlf features some time before you updated the repository. My issue is indeed with the exec line. I will change over to the latest to avoid confusion.

**Comment by JohnOH** [comment]
bash --version
GNU bash, version 4.2.37(1)-release (arm-unknown-linux-gnueabihf)

The problem is infrequent, maybe once every couple of days. It feels like the DNS lookup has an issue.

**Comment by JohnOH** [comment]
I have scripts using burl around once per minute.

**Comment by JohnOH** [comment]
It may be relevant that with my usage multiple instances can happen almost at the same time.

**Comment by falzm** [comment]
Is the error you're facing permanent, or does it only occur from time to time? If you test the same setup on a different architecture (e.g. Linux x86-amd64), does this problem persist?

**Comment by lk86** [comment]
It seems like the DNS for api.thingspeak.com is not resolving. Name or service not known is an error from the system's name resolution (and if the name cannot resolve, then /dev/tcp/ doesn't work). Either the raspi loses connection to the internet or that site goes offline or the DNS resolution is just being stupid.

**Comment by falzm** [comment]
Looks like it, yes.

**Comment by JohnOH** [comment]
I haven't tried on other than Raspberry Pi ARM architecture. Since it only happens infrequently in terms of the number of invocations I think it would be difficult to simulate. 

My thoughts too @ik86.

I expect to see odd errors but the knock on effect of this one is that text is sent to descriptor 3. I have a pipe linked to an external device which sees a stream of characters when the error happens. My real problem is the external device reacts badly to the stream of characters.

I was hoping to be able to check if the exec 3 was successful before sending the printf.

Intrigued how descriptor 3 could be crossed with my pipe.

**Comment by falzm** [comment]
Well I'm sorry but based on this description of the problem I'm not sure this is related to the script – not that it isn't, but if so I honestly have no idea how to "fix" this.

I appreciate your interest for this thing, but I insist: you should not use it for _serious_ purpose, it is not reliable. `curl` works very well on minimal environment such as RaspberryPIs, I recommend you use it.

**Comment by JohnOH** [comment]
Thanks for your work. I will look at testing the -1 return code when exec fails.

**Comment by JohnOH** [comment]
I'll give this a spin:

    if exec 3<>/dev/tcp/${host}/${HTTP_PORT}; then

**Comment by JohnOH** [comment]
Appears to clear up the problem I was having. I have submitted  a pull.
